### ISSUE TITLE
Process crashing due to fdisk command giving empty response

### ISSUE THREAD

**Issue by HugoJPMartin** [TuxML/Core#2]
```
dev: Pulling from tuxml/tuxmldebian
Digest: sha256:1315ddd3cfacb0bcab8aacffadc7a4c0ccc55f422c33626d5c5d8ba6b10f6640
Status: Image is up to date for tuxml/tuxmldebian:dev

=============== Docker number 1 ===============

------ Running runandlog.py ... ------

00:00:00 [2018-09-12 14:58:17 CEST] [args_handler] Cleaning previous compilation
00:00:00 make: Entering directory '/TuxML/linux-4.13.3'
00:00:06 make: Leaving directory '/TuxML/linux-4.13.3'
Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 352, in <module>
    main()
  File "/TuxML/tuxml.py", line 308, in main
    targs.args_handler()
  File "/TuxML/tuxml_argshandler.py", line 149, in args_handler
    tset.NB_CORES = int(tenv.get_hardware_details()["cpu_cores"])
  File "/TuxML/tuxml_environment.py", line 203, in get_hardware_details
    "mechanical_drive": __get_type_of_disk()
  File "/TuxML/tuxml_environment.py", line 127, in __get_type_of_disk
    disk = __get_disk_docker()
  File "/TuxML/tuxml_environment.py", line 152, in __get_disk_docker
    return subprocess.check_output("fdisk -l | grep Disk -m1", shell=True).decode().split()[1].split("/")[2].strip(":")
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'fdisk -l | grep Disk -m1' returned non-zero exit status 1

Processing output.log ...
CID array: []
Cid unfound, no output.log file has been sent


Fetch logs and .config file from container:76afd3331303 to the folder ./Logs/20180912_145815
Error response from daemon: lstat /var/lib/docker/devicemapper/mnt/a09a38a02152a994be04a3119cc0d1fd1741b5918d669402b9a8b076fdcb86cb/rootfs/TuxML/linux-4.13.3/logs/std.log: no such file or directory
Error response from daemon: lstat /var/lib/docker/devicemapper/mnt/a09a38a02152a994be04a3119cc0d1fd1741b5918d669402b9a8b076fdcb86cb/rootfs/TuxML/linux-4.13.3/logs/err.log: no such file or directory
Error response from daemon: lstat /var/lib/docker/devicemapper/mnt/a09a38a02152a994be04a3119cc0d1fd1741b5918d669402b9a8b076fdcb86cb/rootfs/TuxML/linux-4.13.3/.config: no such file or directory

```

https://github.com/TuxML/Core/blob/master/tuxml_environment.py#L153

While manually running the docker image, the fdisk command does not return anything either.

**Comment by mipicard** [comment]
This is a "successful" result I have got on my computer :
```
$ sudo ./MLfood.py 1

Advice:
Without '--dev' the image is the functionnal version 'prod' of tuxmldebian:prod (stable)
With '--dev' it will use the current dev version tuxmldebian:dev (possibly unstable)
     Real Command: ./MLfood.py 1

Recovering the last docker image tuxml/tuxmldebian:prod

prod: Pulling from tuxml/tuxmldebian
0bd44ff9c2cf: Pull complete 
5fa685ba5423: Pull complete 
96a08b5311cf: Pull complete 
61f6fba8812b: Pull complete 
55a4c6354405: Pull complete 
5ae523a6f9d3: Pull complete 
19c2d0ddee12: Pull complete 
36dbf8699e64: Pull complete 
33b7997daf16: Pull complete 
87bdf4031496: Pull complete 
42a322b98737: Pull complete 
d32314ca0e64: Pull complete 
dceec293b2ed: Pull complete 
dcf0ece006e5: Pull complete 
e421a5d829e5: Pull complete 
7da045ee4ce5: Pull complete 
Digest: sha256:1315ddd3cfacb0bcab8aacffadc7a4c0ccc55f422c33626d5c5d8ba6b10f6640
Status: Downloaded newer image for tuxml/tuxmldebian:prod

=============== Docker number 1 ===============

------ Running runandlog.py ... ------

00:00:00 [2018-09-12 15:15:48 CEST] [args_handler] Cleaning previous compilation
00:00:00 make: Entering directory '/TuxML/linux-4.13.3'
00:00:08 make: Leaving directory '/TuxML/linux-4.13.3'
00:00:08 [2018-09-12 15:15:56 CEST] [get_environment_details] Getting environment details
00:00:08 [2018-09-12 15:15:56 CEST] [get_compilation_details] Unable to find tuxml.conf
00:00:09     ==> hardware
00:00:09       --> cpu: Intel(R) Core(TM) i3-3227U CPU @ 1.90GHz
00:00:09       --> cpu_cores: 4
00:00:09       --> cpu_freq: 1799
00:00:09       --> mechanical_drive: 1
00:00:09       --> ram: 7960420
00:00:09       --> arch: x86_64
00:00:09     ==> system
00:00:09       --> os: Linux
00:00:09       --> distribution: debian
00:00:09       --> kernel: 4.15.0-33-generic
00:00:09       --> distrib_version: 9.5
00:00:09     ==> compilation
00:00:09       --> core_used: 4
00:00:09       --> gcc_version: 6.3.0-18+deb9u1
00:00:09       --> libc_version: 2.24-11+deb9u3
00:00:09       --> tuxml_version: pre-alpha v0.2
00:00:09       --> docker_image: 
00:00:09       --> incremental_mod: 0
00:00:09       --> git_branch: 
00:00:09 [2018-09-12 15:15:57 CEST] [get_package_manager] Finding package manager
00:00:09 [2018-09-12 15:15:57 CEST] [get_package_manager] Package manager is apt-get
00:00:09 [2018-09-12 15:15:57 CEST] [update_system] Updating packages repositories
00:00:13 [2018-09-12 15:16:01 CEST] [update_system] Packages repositories updated
00:00:13 [2018-09-12 15:16:01 CEST] [install_minimal_dependencies] Installing minimal dependencies
00:00:13 [2018-09-12 15:16:01 CEST] [install_packages] Installing packages : gcc make binutils util-linux e2fsprogs bc
00:00:14 [2018-09-12 15:16:02 CEST] [install_packages] All the packages were found and installed
00:00:14 [2018-09-12 15:16:02 CEST] [install_minimal_dependencies] Minimal dependencies successfully installed.
00:00:14 [2018-09-12 15:16:02 CEST] [install_default_dependencies] Installing default dependencies
00:00:14 [2018-09-12 15:16:02 CEST] [install_packages] Installing packages : kmod jfsutils xfsprogs btrfs-progs pcmciautils ppp grub iptables openssl reiserfsprogs squashfs-tools quotatool nfs-kernel-server procps mcelog libcrypto++6 apt-utils gcc-6-plugin-dev libssl-dev
00:00:38 [2018-09-12 15:16:26 CEST] [install_packages] All the packages were found and installed
00:00:38 [2018-09-12 15:16:26 CEST] [install_default_dependencies] Default dependencies successfully installed.
00:00:38 [2018-09-12 15:16:26 CEST] [gen_config] Randomising new KCONFIG_FILE
00:00:38 [2018-09-12 15:16:26 CEST] [gen_config] KCONFIG_ALLCONFIG=/TuxML/tuxml.config make -C /TuxML/linux-4.13.3 randconfig
00:00:42 KCONFIG_SEED=0x8D2164B3
00:00:43 [2018-09-12 15:16:31 CEST] [compilation] Compilation in progress
00:13:40 [2018-09-12 15:29:28 CEST] [compilation] Compilation done
00:13:40 [2018-09-12 15:29:28 CEST] [launcher] Successfully compiled in 00:12:57
00:13:40 [2018-09-12 15:29:28 CEST] [boot_try] Launching boot test on kernel
00:13:40 WARNING: missing /lib/modules/4.15.0-33-generic
00:13:40 Ensure all necessary drivers are built into the linux image!
00:13:40 depmod: ERROR: could not open directory /lib/modules/4.15.0-33-generic: No such file or directory
00:13:40 depmod: FATAL: could not search modules: No such file or directory
00:13:42 depmod: WARNING: could not open /var/tmp/mkinitramfs_fVH3oZ/lib/modules/4.15.0-33-generic/modules.order: No such file or directory
00:13:42 depmod: WARNING: could not open /var/tmp/mkinitramfs_fVH3oZ/lib/modules/4.15.0-33-generic/modules.builtin: No such file or directory
00:13:43 Could not initialize SDL(No available video device) - exiting
00:15:38 [2018-09-12 15:31:26 CEST] [boot_try] More than 60 attempts at reading, possible infinite loop in boot process, interrupting
00:15:38 [2018-09-12 15:31:26 CEST] [send_data] Sending compilation and tests results to database
00:15:38 [2018-09-12 15:31:26 CEST] [get_compressed_sizes] Computing compressed kernels
00:18:31 [2018-09-12 15:34:19 CEST] [send_data] Successfully sent info to db
00:18:31 [2018-09-12 15:34:19 CEST] [main] DATABASE CONFIGURATION ID=116710

Processing output.log ...
CID found 116710
CID array: ['116710']

Fetch logs and .config file from container:da6356177acc to the folder ./Logs/20180912_151539

Cleaning containers . . .
da6356177acc
da6356177acc

Clean done!

===============================================

Your tamago... database Irma_DB ate 1 compilations data, come back later to feed it!

Total number of containers used: 1
Number of compilations in a container: 1 ( 1 basic compilation + 0 incremental compilations )
Total number of compilations: 1

Checking local logs size ...
You have 0.37 Mo of logs files, do not forget to clean up your logs.
```
Surprisingly, the compilation seems to happen outside of the container.

**Comment by FAMILIAR-project** [comment]
issue now in dev ProjetIrma
